add flag for file permission comparision
jeffkaufman/icdiff pull request #197
Opened 2022-04-06 09:37 UTC by hellow554

Two files can not only be compared by file content, but also by file
permissions. This is similar to file types (pipe, links, regular).

It is behind the command line option `-P` or `--permissions`

2022-04-06 13:24 UTC, jeffkaufman requested changes
Looks good, but needs tests

2022-04-06 13:24 UTC, jeffkaufman commented on icdiff
> +        modea = os.lstat(a).st_mode
nit: `mode_a`, `mode_b`

2022-04-06 13:30 UTC, hellow554 commented on icdiff
> +        modea = os.lstat(a).st_mode
What do you think about [`stat.filemode`](https://docs.python.org/3/library/stat.html#stat.filemode) ?

2022-04-06 13:32 UTC, hellow554 commented
Can you tell/show me how your tests work? I see the test folder but no information on how to write a test.

2022-04-06 13:42 UTC, jeffkaufman commented on icdiff
> +        modea = os.lstat(a).st_mode
That looks good!

2022-04-06 13:45 UTC, jeffkaufman commented
> Can you tell/show me how your tests work? I see the test folder but no information on how to write a test.

To run the tests: `./test.sh python3`

There are (minimal, sorry!) docs at the beginning of https://github.com/jeffkaufman/icdiff/blob/master/test.sh

In this case, because you can't count on the golden files already having a certain set of permissions, I think you might need to do something like:

1. create `tests/permissions-a` and `tests/permissions-b`
2. Make test.sh manually set the permissions on those two files
3. Copy existing tests, adding a `check_gold` statement

2022-04-06 13:59 UTC, hellow554 commented on icdiff
> +        modea = os.lstat(a).st_mode
![grafik](https://user-images.githubusercontent.com/921462/161992003-dda34d9b-2c17-4d04-b2db-b31828079a1c.png)

2022-04-06 14:01 UTC, jeffkaufman commented on icdiff
> +        modea = os.lstat(a).st_mode
nice!

2022-04-07 08:50 UTC, hellow554 commented
So, I did a thing, or two.
Sorry for the delay, hadn't had any time yesterday.

I extended the tests, hope this is okay.

Can you explain me how you format your code? I tried to use black or yapf3, but none of them matched your coding style.

2022-04-08 01:55 UTC, jeffkaufman approved these changes

2022-04-08 01:55 UTC, jeffkaufman commented
Looks good!

The coding style is old and idiosyncratic. At some point I should probably run the whole thing through an auto formatter.  Suggestions?

2022-04-08 01:56 UTC, merged

2022-04-08 05:10 UTC, hellow554 commented
Thanks for the merge.

I really like `black` as formatter. Give it a try 😉

2022-04-08 14:53 UTC, jeffkaufman commented
> I really like black as formatter.

Done!

Also, released this in 2.0.5 and pushed to PyPi